project_name: sushi

builds:
  - binary: sushi

    main: ./cmd/sushi/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Build={{.Version}}

    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'
      - '6'
      - '5'
    gomips:
      - hardfloat
      - softfloat

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: openbsd
        goarch: arm

archives:
  - id: sushi
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

